### ISSUE TITLE
CoffeeScript support?

### ISSUE THREAD

**Issue by Sivli-Embir** [Slava/tern-meteor-sublime#1]
Awesome package! It does not seem to work in CoffeeScript though, any configuration necessary or is that a feature request?

**Comment by Slava** [comment]
See https://github.com/marijnh/tern/issues/226 https://github.com/marijnh/tern/issues/240

**Comment by Sivli-Embir** [comment]
Hmm ok, not sure I can budget that right now. Closing as it is not an issue with this package. Thanks!
