### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by leebenson** [Slava/tern-meteor-sublime#10]
Using this with Sublime v3, on a moderately sized Meteor app, I get this every time:

![screen shot 2015-04-07 at 12 04 52](https://cloud.githubusercontent.com/assets/719722/7021915/62622016-dd1e-11e4-8d52-daa2d33bc80e.png)

**Comment by Slava** [comment]
On bigger projects the startup time will take longer time. Usually pressing "Cancel" and giving it a couple of seconds works fine for me.

**Comment by Pushplaybang** [comment]
yeah this is pretty annoying, it happens every few minutes, or after spending a minute or two in the browser, I recall that codeIntel used to suffer from a similar issue and there was a bit of hack to fix it....  any chance you're going to look at this ?

**Comment by marxo** [comment]
I can confirm that this issue is pretty much making the package unusable with bigger projects. Indexing crashes Sublime.

**Comment by leebenson** [comment]
yup, I'm still getting the same issue. I switched to WebStorm and haven't looked back.

**Comment by marxo** [comment]
I'm pretty sure the bottleneck is PyV8 combined with TernJS, here's a reference https://github.com/emmetio/sublime-tern/issues/36, not actually this packages issue.

**Comment by marxo** [comment]
The **solution** seems to be: Uninstall `TernJS` package with PyV8, and install https://github.com/marijnh/tern_for_sublime which uses Node.js instead of PyV8. No hangs.

**Comment by artisin** [comment]
I found the `All Autocomplete` was the root cause for my timed out issues. Removed the package and now everything works perfectly.

**Comment by lucascurti** [comment]
@marxo Did you manage to make tern_for_sublime work with Meteor?

**Comment by marxo** [comment]
@lucatros Yes, `tern_for_sublime` works good with Meteor. No hickups.

**Comment by lucascurti** [comment]
Can you please share some tip on how to make it work? I installed it but doesn't seem to work. Since TernJS seems to be packed into the "tern-meteor-sublime" package I'm not sure how I should uninstall without uninstalling the complete package. Thanks.
