### ISSUE TITLE
Failed to start server error

### ISSUE THREAD

**Issue by Morganjackson** [Slava/tern-meteor-sublime#12]
Has anyone come across this error before? 

![screen shot 2015-04-12 at 1 18 39 pm](https://cloud.githubusercontent.com/assets/833805/7104263/855e1056-e116-11e4-9242-dab0c8be012e.png)

**Comment by Slava** [comment]
This happens when your project is way too big and Node tries to open all these files to analyze.

On your OS, you can bump the limit of max open files from 256 to something higher: http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Comment by StanLindsey** [comment]
So, I've used a variety of methods to increase my max open limit, even up to 1024 from 256 using LaunchCTL. The error still appears. 

The link you suggested @Slava says to move to [graceful-fs](https://github.com/isaacs/node-graceful-fs) - why don't we do that and solve all this.

**Comment by lnmunhoz** [comment]
@StanLindsey Did you fix it?

**Comment by StanLindsey** [comment]
Yeah, I think so. Though it sort of needs more testing.
Try it out as follows:
1. Remove Slava's version of the package from sublime
2. Find your Sublime Text packages path by opening the Sublime Console (Ctrl+`) and running:
`sublime.packages_path()`
3. Cd in and clone to your package path and clone my repo, until this is added to Slava's.
`$ cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages`
`$ git clone https://github.com/StanLindsey/tern-meteor-sublime.git Stan-Tern-Meteor`
4. `cd Stan-Tern-Meteor && npm install`
5. Restart Sublime

Let me know if any issues.

**Comment by lnmunhoz** [comment]
It was missing `npm install`, but after that, works! +1 @StanLindsey Thanks!

**Comment by maddijoyce** [comment]
Just for clarity's sake, I think that should be 
`cd Stan-Tern-Meteor && npm install`

Thanks for the fix @StanLindsey

**Comment by arvi** [comment]
I tried @StanLindsey's solution but I'm still getting the error even after restarting Sublime editor.

![screen shot 2016-06-26 at 11 14 13 pm](https://cloud.githubusercontent.com/assets/653750/16363127/c91f5712-3bf3-11e6-9d6c-d217dd346315.png)

I've inspected the package.json file:

```
{
  "name": "tern_for_sublime",
  "license": "MIT",
  "version": "0.4.0",
  "author": "Marijn Haverbeke <marijnh@gmail.com>",
  "description": "Sublime Text package for Tern",
  "repository": {
    "type": "git",
    "url": "git://github.com/marijnh/tern_for_sublime.git"
  },
  "dependencies": {
    "graceful-fs": "^4.1.3",
    "tern": ">=0.5"
  }
}
```

Meteor version: **1.3.4.1**
NPM version: **2.1.18**
Machine: **OSX El Capitan 10.11.3**

I've also added this in my `Settings - User` as mentioned in the documentation.

```
    "auto_complete_triggers":
    [
        { "characters": "<", "selector": "text.html" },
        { "characters": ".", "selector": "source.js" }
    ]
```

I'm not sure what I missed. 

Thanks :smile:

**Comment by HintikkaKimmo** [comment]
Followed the instructions provided by @StanLindsey and thanks for those but it does not seem to fix this. I can see that graceful-fs is now installed but I continue to get the same error. 

Only difference is that now I get the error 2 x every time once from TernJS and once from the Stan-TernJS

**Comment by mikeygcooper** [comment]
The fix provided by @StanLindsey does not work for me either :(

**Comment by arvi** [comment]
I had no choice but to uninstall it for the meantime since everytime I time I type F (trying to type FlowRouter) this error keeps popping up. I'm not sure how others made it work.

**Comment by curlynux** [comment]
hi, i solved the issue by installing TernJS mannualy with npm like this `sudo npm -g install tern` and after that i `cd` to my project and type `tern` to start the server after that i just opened i new terminal  

> ctrl + alt + t

and `cd` again to my project then typed `subl ../my_project` to open sublime with my project  folder. i try to test the package by typed many js function and meteor methods all worked           nicely no error popping up. yes it's fastidious all ways do that but it's work fine for now so the author or community have to solve the issue thank you and have a nice day/night

**Comment by sdwager** [comment]
https://jaredbarriere.wordpress.com/2016/08/02/sublime-text-3-meteor-auto-complete-ternjs/

This worked for me.

**Comment by nunohvidal** [comment]
@sdwager suggestion worked for me
> https://jaredbarriere.wordpress.com/2016/08/02/sublime-text-3-meteor-auto-complete-ternjs/

**Comment by Nikitozz13** [comment]
@sdwager suggestion works for me too.
macOS Sierra 10.12.5 (16F73)

> https://jaredbarriere.wordpress.com/2016/08/02/sublime-text-3-meteor-auto-complete-ternjs/

With terminal go to
`cd Users/<YOUR_USERNAME>/Library/Application\ Support/Sublime\ Text\ 3/Packages/Meteor\ Autocomplete\ \(TernJS\)/node_modules/tern/bin/
`
And modify `tern` file like described in link above

**Comment by martianmartian** [comment]
just remove the silly ternjs
