### ISSUE TITLE
ST3 Hanging while typing

### ISSUE THREAD

**Issue by jaredtmartin** [Slava/tern-meteor-sublime#18]
It may or may not be a dup of #15. My problem is similar, but for me it happens when I'm typing.  It happens when I type the first letter of each word and when I type a period.  In activity monitor it shows Sublime as the top CPU user.

**Comment by Slava** [comment]
I think it is the same. When you type in the first letter or a period, the plugin is starting up which takes a lot of time.

**Comment by Slava** [comment]
I will close this as a dup.
