### ISSUE TITLE
Obtrusive tooltip in function arguments

### ISSUE THREAD

**Issue by Angarsk8** [Slava/tern-meteor-sublime#24]
I've been recently doing some meteor work and discovered the sublime text package you developed on top of TernJs. I've liked a lot so far! But I have a problem, every time I write a function I cannot get autocomplete for the arguments because the tooltip with the information about the function blocks the arguments!! It is very obtrusive and I don't know how to get rid of it. The thing is that in the videos where you show the package I don't see that problem. Can you help me?

Thanks!

**Comment by Slava** [comment]
You should set the `tern_argument_hints` option: https://github.com/Slava/tern-meteor-sublime/blob/master/Original_README.md#configuration

**Comment by Angarsk8** [comment]
Thanks Slava! Have a good day! :+1:
