### ISSUE TITLE
sublime 3 hangs/crashes on js files outside of meteor project 

### ISSUE THREAD

**Issue by orangewise** [Slava/tern-meteor-sublime#4]
My sublime goes to non-responding when I open a file outside of a meteor project... Plugin works great inside meteor.

**Comment by kevincharm** [comment]
I believe I have the same issue. Are you getting the EMFILE (too many open files) error?

**Comment by Slava** [comment]
What would be an example of a path? I think I can debug this. The problem is probably in the fact that I traverse the parent directories looking for `.meteor` and at some point I just hit "access denied" or similar.

**Comment by kevincharm** [comment]
My working directory would be something like `/Users/hellstad/dev/someproject` Currently it throws the error on pretty much every file.
![screen shot 2015-03-15 at 10 10 04 pm](https://cloud.githubusercontent.com/assets/10385659/6657401/df69c23a-cb85-11e4-86db-18990a183519.png)

**Comment by Slava** [comment]
@hellstad are you opening a stand-alone JS file?

**Comment by orangewise** [comment]
@hellstad I do not get the EMFILE error, maybe I do not wait long enough :)

@Slava My sublime also 'hangs' when I open a single js file (outside of meteor)...

**Comment by kevincharm** [comment]
@Slava yeah standalone js files.

**Comment by Slava** [comment]
Thanks everyone for this report. I fixed it in the version 1.0.3 of this plugin. It soon should be available as an update on Package Control!

Not it is all smooth and steady :3

**Comment by orangewise** [comment]
Great job @Slava, problem solved!

**Comment by kevincharm** [comment]
Yep, no problems so far...  thanks @Slava :)
