### ISSUE TITLE
no such file or directory 'Users/slava/log.txt'

### ISSUE THREAD

**Issue by ryandeussing** [Slava/tern-meteor-sublime#5]
![sublime text](https://cloud.githubusercontent.com/assets/216835/6658787/05f7e3b8-cb4b-11e4-9687-d4434c007984.png)

I've just installed, added settings, and restarted and am getting this error. Thanks.

**Comment by Slava** [comment]
Oh my, did I commit my debugging by mistake? Give me a couple of minutes to fix this.

**Comment by Slava** [comment]
Should be fixed. Now wait until Package Control updates the index and then update the package.

**Comment by Slava** [comment]
Thanks for the report!

**Comment by ryandeussing** [comment]
Thanks!
